management:
  endpoints:
    web:
      exposure:
        include: "health,info,hawtio,prometheus"
    health:
      show-details: when_authorized
  endpoint:
    shutdown:
      enabled: false

hawtio:
  authenticationEnabled: true

spring:
  devtools:
    add-properties: false
  servlet:
    session:
      cookie:
        same-site: strict

logging:
  level:
    root: INFO
    org.springframework.web: INFO
