spring:
  application:
    name: "generic-server-spring-boot"
  profiles:
    active: "local"
  jmx:
    enabled: true
  datasource:
    driver-class-name: "org.postgresql.Driver"
    hikari:
      pool-name: "EnterprisePostgresPool"
      maximum-pool-size: 10
      minimum-idle: 2
      idle-timeout: 600000
      max-lifetime: 1800000
      connection-timeout: 30000
      connection-test-query: "SELECT 1"

server:
  port: 8080

springdoc:
  show-actuator: true
  swagger-ui:
    path: "/swagger-ui"
