management:
  endpoints:
    web:
      exposure:
        include: "*"
    health:
      show-details: when_authorized

hawtio:
  authenticationEnabled: false

spring:
  servlet:
    session:
      cookie:
        same-site: strict
  security:
    user:
      name: "devuser"
      password: "{noop}devpassword"
      roles: USER, ACTUATOR, ADMIN

logging:
  level:
    root: INFO
    org.springframework.web: INFO
