management:
  endpoints:
    web:
      exposure:
        include: "*"
    health:
      show-details: when_authorized

hawtio:
  authenticationEnabled: false

spring:
  servlet:
    session:
      cookie:
        same-site: strict
  security:
    user:
      name: "devuser"
      password: "{noop}devpassword"
      roles: USER, ACTUATOR, ADMIN
  datasource:
    url: "jdbc:postgresql://aws-1-ap-south-1.pooler.supabase.com:6543/postgres?user=postgres.hwnzjlovbrecaizjoqsn&password=${DB_PASSWORD}&sslmode=verify-full&sslrootcert=classpath:supabase.crt"

logging:
  level:
    root: INFO
    org.springframework.web: INFO
