management:
  endpoints:
    web:
      exposure:
        include: "health,info,hawtio,prometheus,jolokia"
    health:
      show-details: when_authorized
  endpoint:
    shutdown:
      enabled: false

hawtio:
  authenticationEnabled: false

spring:
  devtools:
    add-properties: false
  servlet:
    session:
      cookie:
        same-site: strict
  datasource:
    url: "jdbc:postgresql://aws-1-ap-south-1.pooler.supabase.com:6543/postgres?user=postgres.hwnzjlovbrecaizjoqsn&password=${DB_PASSWORD}&sslmode=verify-full&sslrootcert=/app/certs/supabase.crt"

logging:
  level:
    root: INFO
    org.springframework.web: INFO
