management:
  endpoints:
    web:
      exposure:
        include: "health,info,hawtio,jolokia,prometheus"
    health:
      show-details: when_authorized

hawtio:
  authenticationEnabled: false

spring:
  security:
    user:
      name: "devuser"
      password: "{noop}devpassword"
      roles: USER, ACTUATOR, ADMIN

logging:
  level:
    root: INFO
    org.springframework.web: INFO
