management:
  endpoints:
    web:
      exposure:
        include: "*"
    health:
      show-details: when_authorized

hawtio:
  authenticationEnabled: false

spring:
  servlet:
    session:
      cookie:
        same-site: strict
  security:
    user:
      name: "devuser"
      password: "{noop}devpassword"
      roles: USER, ACTUATOR, ADMIN
  datasource:
    url: "jdbc:postgresql://aws-1-ap-south-1.pooler.supabase.com:6543/postgres?user=postgres.hwnzjlovbrecaizjoqsn&password=${DB_PASSWORD}&sslmode=verify-full&sslrootcert=${user.dir}/src/main/resources/certs/supabase.crt"
  kafka:
    ssl:
      truststore-location: classpath:certs/client.truststore.jks
      truststore-password: ${KAFKA_SSL_TRUSTSTORE_PASSWORD}
      keystore-location: classpath:certs/client.keystore.p12
      keystore-password: ${KAFKA_SSL_KEYSTORE_PASSWORD}
      key-password: ${KAFKA_SSL_KEY_PASSWORD}

logging:
  level:
    root: INFO
    org.springframework.web: INFO
